export enum CONFIGURATION {
  MONGO_URL = 'MONGO_URL',
  JWT_SECRET_KEY = 'JWT_SECRET_KEY',
  JWT_EXPIRE_TIME = 'JWT_EXPIRE_TIME',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
}
